name: Upload Releases
on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Remove old release, fetch artifacts, repackage binaries and upload new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BUILDNUM_DATE: "2015-04-01"
        run: bash scripts/gha/make_release.sh "Xash3D FWGS" "${{ github.ref_name }}"
